### PR TITLE
"your_first_code"

### PR DESCRIPTION
**Pull request by relishthat**
I am requesting the clean code, with the answer of a proper heading and print function.

anyways..
here's the code even though it's in the file.
I'm trying to understand what it means to "fork" a file, this is my attempt to do that.
===================================
#include <stdio.h>
int main()
{
  int i;
  for (i = 0; i < 10; i++)
  for (i = 0; i < 32; i++)
  {

    printf("Hello Holberton\n");
  }
  return 0;
}
=============================

The other code "32istheAnswer", was kind of my attempt and learning of the language and getting "helloHolberton" 32 times. 

Thank You,
SamAlberts

### CODE REVIEW

**Comment by patchoulibluez** [comment]
p.s.
I do not know why the characters in the text turned bold. But, I'll keep trying to submit the answer to the school application, I don't know why I can't?

Thanks.
SamiAlberts

**Comment by momomed007** [comment]
I cant continue im tired

**Comment by ministermikemiz** [comment]
Thanks I'm tired as wellWill work on this later.
    On Monday, January 6, 2020, 10:28:20 AM EST, momomed007 <notifications@github.com> wrote:  
 
 
I cant continue im tired

**Comment by patchoulibluez** [comment]
I'm just glad I figured it out. There was actually more than one way to do
it.. tired or not u can get an "infinite" answer, a manual answer that
interacts ih the person working with th the code, and the straight answer
depending on what is wanted. It made me happy, I def learned something.

**Comment by ministermikemiz** [comment]
Okay I'm going to make some progress. Going to do some reading first.I will have to wait for the june class though.Missing the deadline.

Sent from Yahoo Mail on Android 
 
  On Tue, Jan 7, 2020 at 12:45 PM, Sami<notifications@github.com> wrote:   I'm just glad I figured it out. There was actually more than one way to do
it.. tired or not u can get an "infinite" answer, a manual answer that
interacts ih the person working with th the code, and the straight answer
depending on what is wanted. It made me happy, I def learned something.

**Pull request closed without merging**
